kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: java
  SourceLocation: build/libs/ceeredhat-0.0.3-all.jar
  SourceType: binary
  Ports:
  - 8778/TCP
  - 8080/TCP
  - 8443/TCP
  Application: app
  Project: ceeredhat
  Name: ceeredhat
  Envs:
  - Name: KTOR_ENV
    Value: prod
  Url:
  - Name: ceeredhat
    Port: 8080
